Repository lvisei/li-zelda-assets, pull requests merged in 2023-05, with the labels that each got.

#2 feat: 标注数据新增 group 相关字段
  docs/dev/configs/data.json
Labels: feature

#3 feat: 数据新增标注颜色字段
  docs/dev/configs/data.json
Labels: feature

#6 fix: 修复当前应用中部分问题
  docs/dev/configs/app-config.ts
  docs/dev/configs/data.json
  package.json
  src/utils/index.ts
  src/widgets/ZeldaLayerControl/Component.less
  src/widgets/ZeldaMobileLayout/FilterPanel/SearchBody/index.less
  src/widgets/ZeldaMobileLayout/FilterPanel/SearchBody/index.tsx
  src/widgets/ZeldaMobileLayout/FilterPanel/index.less
  src/widgets/ZeldaMobileLayout/FilterPanel/index.tsx
  src/widgets/ZeldaMobileLayout/MarkLayer/index.less
  src/widgets/ZeldaMobileLayout/MarkLayer/index.tsx
  src/widgets/ZeldaMobileLayout/RegisterSvgs/index.tsx
  src/widgets/ZeldaMobileLayout/types.ts
Labels: bugfix

#7 fix: 修复 npm publish 失败的问题
  package.json
Labels: bugfix

#8 fix: 修复组件样式 UMD 打包问题
  package.json
  src/widgets/ZeldaLayerControl/Component.less
  src/widgets/ZeldaLayerControl/Component.tsx
  src/widgets/ZeldaLayerControl/constants.ts
  src/widgets/ZeldaMobileLayout/FilterPanel/SearchBody/index.less
  src/widgets/ZeldaMobileLayout/FilterPanel/SearchBody/index.tsx
  src/widgets/ZeldaMobileLayout/FilterPanel/constants.ts
  src/widgets/ZeldaMobileLayout/FilterPanel/index.less
  src/widgets/ZeldaMobileLayout/FilterPanel/index.tsx
  src/widgets/ZeldaMobileLayout/MarkLayer/constants.ts
  src/widgets/ZeldaMobileLayout/MarkLayer/index.less
  src/widgets/ZeldaMobileLayout/MarkLayer/index.tsx
  src/widgets/ZeldaZoomControl/Component.less
  src/widgets/ZeldaZoomControl/Component.tsx
  src/widgets/ZeldaZoomControl/constants.ts
Labels: bugfix

#9 chore: v0.0.2
  package.json
  src/index.ts
Labels: ignore-for-release

#12 feat: 添加 Mark 标记功能
  src/hooks/useAchieved.ts
  src/utils/index.ts
  src/utils/store.ts
  src/widgets/ZeldaMobileLayout/MarkLayer/Stamp.tsx
  src/widgets/ZeldaMobileLayout/MarkLayer/index.less
  src/widgets/ZeldaMobileLayout/MarkLayer/index.tsx
Labels: feature

#10 fix: 订正瓦片图层服务
  docs/dev/configs/app-config.ts
Labels: bugfix

#14 feat: Marker UI优化和按序展示问题
  docs/dev/configs/app-config.ts
  docs/dev/configs/data.json
  package.json
  src/utils/index.ts
  src/widgets/ZeldaLayerControl/Component.tsx
  src/widgets/ZeldaLayerControl/registerForm.ts
  src/widgets/ZeldaMobileLayout/FilterPanel/index.less
  src/widgets/ZeldaMobileLayout/FilterPanel/index.tsx
  src/widgets/ZeldaMobileLayout/MarkLayer/index.less
  src/widgets/ZeldaMobileLayout/MarkLayer/index.tsx
  src/widgets/ZeldaMobileLayout/RegisterSvgs/index.tsx
  src/widgets/ZeldaMoreControl/Component.less
  src/widgets/ZeldaMoreControl/Component.tsx
  src/widgets/ZeldaMoreControl/constants.ts
  src/widgets/ZeldaMoreControl/index.md
  src/widgets/ZeldaMoreControl/index.ts
  src/widgets/ZeldaMoreControl/registerForm.ts
  src/widgets/index.ts
Labels: feature

#15 fix: 修复分享时图层数据问题
  README.md
  docs/dev/configs/app-config.ts
  src/widgets/TemplateComponent/Component.tsx
  src/widgets/TemplateComponent/demos/constants.ts
  src/widgets/TemplateComponent/demos/default.tsx
  src/widgets/TemplateComponent/index.md
  src/widgets/TemplateComponent/index.ts
  src/widgets/TemplateComponent/registerForm.ts
  src/widgets/ZeldaLayerControl/Component.tsx
  src/widgets/ZeldaLayerControl/registerForm.ts
  src/widgets/ZeldaMobileLayout/FilterPanel/index.tsx
  src/widgets/ZeldaMobileLayout/MarkLayer/index.tsx
  src/widgets/index.ts
Labels: bugfix

#16 chore: v0.0.4
  package.json
Labels: ignore-for-release
